//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee_schedule_tbl
    {
        public int employee_schedule_id { get; set; }
        public int employee_id { get; set; }
        public int day { get; set; }
        public int shift_type_id { get; set; }
        public int priority { get; set; }
        public System.DateTime start_date { get; set; }
        public System.DateTime end_date { get; set; }
    
        public virtual Employee_tbl Employee_tbl { get; set; }
        public virtual ShiftType_tbl ShiftType_tbl { get; set; }
    }
}
