//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Jobs_to_shift_tbl
    {
        public int jobs_to_shift_id { get; set; }
        public int job_id { get; set; }
        public int shift_id { get; set; }
        public int num_employees_requierd { get; set; }
        public System.DateTime request_date { get; set; }
    
        public virtual Jobs_tbl Jobs_tbl { get; set; }
        public virtual Shift_tbl Shift_tbl { get; set; }
    }
}
