//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShiftManager_tbl
    {
        public int shift_manager_id { get; set; }
        public int shift_id { get; set; }
        public Nullable<int> employee_id { get; set; }
    
        public virtual Employee_tbl Employee_tbl { get; set; }
        public virtual Shift_tbl Shift_tbl { get; set; }
    }
}
