//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ToBeWith_tbl
    {
        public int to_be_with_id { get; set; }
        public int shift_id { get; set; }
        public int employeeA_id { get; set; }
        public int employeeB_id { get; set; }
        public int status { get; set; }
        public int priority_id { get; set; }
    
        public virtual Employee_tbl Employee_tbl { get; set; }
        public virtual Employee_tbl Employee_tbl1 { get; set; }
        public virtual Priority_tbl Priority_tbl { get; set; }
        public virtual Shift_tbl Shift_tbl { get; set; }
    }
}
